from app.models.announcement import Announcement
from app.models.contact_message import ContactMessage
from app.models.event import Event
from app.models.gallery import Gallery
from app.models.news import News
from app.models.page import Page
from app.models.tender import Tender
from app.models.tender_document import TenderDocument
from app.models.user import User
from app.models.media import Media
from app.models.mayor import Mayor
from app.models.mayor_page import MayorPage
from app.models.mission_vision import MissionVision
from app.models.organization import Organization