"""Initial Schema

Revision ID: 44a0b5ac1c17
Revises: 
Create Date: 2026-07-30 10:16:26.289468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '44a0b5ac1c17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'published_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('announcements', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('announcements', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('events', 'published_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('events', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('gallery', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('gallery', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('news', 'published_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('news', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('news', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('pages', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('pages', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('pages', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('news', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('news', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('news', 'published_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('gallery', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('gallery', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('events', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('events', 'published_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('announcements', 'updated_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('announcements', 'created_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    op.alter_column('announcements', 'published_at',
               existing_type=mssql.DATETIMEOFFSET(),
               server_default=sa.text('(getdate())'),
               existing_nullable=True)
    # ### end Alembic commands ###
