import type { Tender } from "./TenderTable";

export const tenderData: Tender[] = [
  {
    id: 1,
    title: "Çevre Düzenleme Yapım İşi",
    department: "Fen İşleri Müdürlüğü",
    publishDate: "03 Haziran 2026",
    deadline: "15 Haziran 2026",
    status: "Açık",
    tenderNo: "2026/001",
    method: "4734 Sayılı Kanun 19. Madde Açık İhale Usulü",
    budget: "12.500.000 ₺",
    location: "Onikişubat / Kahramanmaraş",
    description:
      "Onikişubat ilçesi sınırları içerisinde çevre düzenleme, yürüyüş yolları, peyzaj düzenlemesi ve kent mobilyalarının yapım işini kapsamaktadır.",
    pdf: "/documents/tenders/2026-001.pdf",
  },
  {
    id: 2,
    title: "Temizlik Malzemesi Alımı",
    department: "Destek Hizmetleri Müdürlüğü",
    publishDate: "05 Haziran 2026",
    deadline: "18 Haziran 2026",
    status: "Sonuçlandı",
    tenderNo: "2026/002",
    method: "Doğrudan Temin",
    budget: "850.000 ₺",
    location: "Onikişubat Belediyesi",
    description:
      "Belediye hizmet binalarında kullanılacak temizlik malzemelerinin alımı yapılacaktır.",
    pdf: "/documents/tenders/2026-002.pdf",
  },
  {
    id: 3,
    title: "Park ve Bahçe Bakım Hizmeti Alımı",
    department: "Park ve Bahçeler Müdürlüğü",
    publishDate: "08 Haziran 2026",
    deadline: "21 Haziran 2026",
    status: "Açık",
    tenderNo: "2026/003",
    method: "Açık İhale Usulü",
    budget: "4.800.000 ₺",
    location: "Onikişubat İlçesi",
    description:
      "İlçe genelindeki park ve yeşil alanların bakım, sulama ve peyzaj hizmetlerini kapsamaktadır.",
    pdf: "/documents/tenders/2026-003.pdf",
  },
  {
    id: 4,
    title: "Asfalt Yapım ve Onarım İşi",
    department: "Fen İşleri Müdürlüğü",
    publishDate: "10 Haziran 2026",
    deadline: "24 Haziran 2026",
    status: "Açık",
    tenderNo: "2026/004",
    method: "Açık İhale Usulü",
    budget: "28.000.000 ₺",
    location: "Onikişubat",
    description:
      "İlçe genelinde asfalt serimi ve yol bakım-onarım çalışmaları yapılacaktır.",
    pdf: "/documents/tenders/2026-004.pdf",
  },
  {
    id: 5,
    title: "Araç Kiralama Hizmeti",
    department: "Destek Hizmetleri Müdürlüğü",
    publishDate: "14 Haziran 2026",
    deadline: "27 Haziran 2026",
    status: "Sonuçlandı",
    tenderNo: "2026/005",
    method: "Pazarlık Usulü",
    budget: "7.200.000 ₺",
    location: "Belediye Hizmet Binası",
    description:
      "Belediye hizmetlerinde kullanılmak üzere çeşitli araçların kiralanmasını kapsamaktadır.",
    pdf: "/documents/tenders/2026-005.pdf",
  },
  {
    id: 6,
    title: "Bilgisayar ve Donanım Alımı",
    department: "Bilgi İşlem Müdürlüğü",
    publishDate: "18 Haziran 2026",
    deadline: "30 Haziran 2026",
    status: "Açık",
    tenderNo: "2026/006",
    method: "Açık İhale Usulü",
    budget: "3.600.000 ₺",
    location: "Bilgi İşlem Müdürlüğü",
    description:
      "Bilgisayar, monitör, yazıcı ve ağ ekipmanlarının temini gerçekleştirilecektir.",
    pdf: "/documents/tenders/2026-006.pdf",
  },
  {
    id: 7,
    title: "Kültür Merkezi Tadilat Yapım İşi",
    department: "Fen İşleri Müdürlüğü",
    publishDate: "22 Haziran 2026",
    deadline: "06 Temmuz 2026",
    status: "Sonuçlandı",
    tenderNo: "2026/007",
    method: "Açık İhale Usulü",
    budget: "15.000.000 ₺",
    location: "Necip Fazıl Kültür Merkezi",
    description:
      "Kültür merkezinin iç ve dış tadilat işleri ile teknik altyapı yenileme çalışmaları yapılacaktır.",
    pdf: "/documents/tenders/2026-007.pdf",
  },
  {
    id: 8,
    title: "Sosyal Tesisler Gıda Alımı",
    department: "İşletme ve İştirakler Müdürlüğü",
    publishDate: "24 Haziran 2026",
    deadline: "08 Temmuz 2026",
    status: "Açık",
    tenderNo: "2026/008",
    method: "Açık İhale Usulü",
    budget: "2.900.000 ₺",
    location: "Sosyal Tesisler",
    description:
      "Belediyeye bağlı sosyal tesislerde kullanılacak gıda ürünlerinin alımı yapılacaktır.",
    pdf: "/documents/tenders/2026-008.pdf",
  },
  {
    id: 9,
    title: "Kent Mobilyaları Temini",
    department: "Park ve Bahçeler Müdürlüğü",
    publishDate: "26 Haziran 2026",
    deadline: "10 Temmuz 2026",
    status: "Sonuçlandı",
    tenderNo: "2026/009",
    method: "Açık İhale Usulü",
    budget: "5.100.000 ₺",
    location: "İlçe Geneli",
    description:
      "Kamelya, bank, çöp kovası ve diğer kent mobilyalarının temini gerçekleştirilecektir.",
    pdf: "/documents/tenders/2026-009.pdf",
  },
  {
    id: 10,
    title: "Temizlik Araçları Bakım Hizmeti",
    department: "Temizlik İşleri Müdürlüğü",
    publishDate: "29 Haziran 2026",
    deadline: "12 Temmuz 2026",
    status: "Açık",
    tenderNo: "2026/010",
    method: "Hizmet Alımı",
    budget: "1.950.000 ₺",
    location: "Temizlik İşleri Müdürlüğü",
    description:
      "Temizlik araçlarının bakım, onarım ve periyodik servis hizmetleri alınacaktır.",
    pdf: "/documents/tenders/2026-010.pdf",
  },
  {
    id: 11,
    title: "Çocuk Oyun Parkı Yapımı",
    department: "Park ve Bahçeler Müdürlüğü",
    publishDate: "02 Temmuz 2026",
    deadline: "16 Temmuz 2026",
    status: "Açık",
    tenderNo: "2026/011",
    method: "Açık İhale Usulü",
    budget: "8.750.000 ₺",
    location: "Onikişubat İlçesi",
    description:
      "Yeni nesil çocuk oyun alanları ve çevre düzenleme çalışmaları yapılacaktır.",
    pdf: "/documents/tenders/2026-011.pdf",
  },
  {
    id: 12,
    title: "Elektrik Malzemesi Alımı",
    department: "Destek Hizmetleri Müdürlüğü",
    publishDate: "05 Temmuz 2026",
    deadline: "18 Temmuz 2026",
    status: "Sonuçlandı",
    tenderNo: "2026/012",
    method: "Doğrudan Temin",
    budget: "1.100.000 ₺",
    location: "Onikişubat Belediyesi",
    description:
      "Belediye hizmet binalarında kullanılmak üzere elektrik malzemeleri temin edilecektir.",
    pdf: "/documents/tenders/2026-012.pdf",
  },
];